[package]
name = "sparter"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.1.0"
gptman = "1.0.0"
indicatif = "0.16.2"
path-clean = "0.1.0"
structopt = "0.3"

[build-dependencies]
bytesize = "1.1.0"
clap = "2.23"
path-clean = "0.1.0"
structopt = "0.3"
