[package]
name = "sparter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.1.0"
gpt = "2.0.0"
indicatif = "0.16.2"
once_cell = "1.8.0"
regex = "1.5.4"
structopt = "0.3"
