name: Run Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'     
        required: true
      checkout:
        description: 'Checkout repo?'     
        required: false
        default: no

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ github.event.inputs.checkout == 'true' || github.event.inputs.checkout == 'yes' }}


      - name: Run the command
        run: ${{ github.event.inputs.command }}