name: Leaderboard Update

on:
  repository_dispatch:
    types: [leaderboard_update]

jobs:
  save-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Collect data
      env:
        DATA: ${{ github.event.client_payload.data }}
      run: echo "$DATA" > leaderboard.json

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan temp-branch
        git add .
        git commit -m "Update leaderboard.json"
        git branch -D leaderboard || true
        git checkout -b leaderboard
        git push -f origin leaderboard
