#!/bin/bash

export CMAKE=/usr/local/bin/cmake
export CMAKE_TOOLCHAIN_FILE=/opt/cmake-linux32.cmake

export AS=/usr/bin/as
export AR=/usr/bin/ar
export CC=/usr/bin/gcc
export CPP=/usr/bin/cpp
export CXX=/usr/bin/g++
export LD=/usr/bin/ld
export FC=/usr/bin/gfortran


echo > /opt/cmake-linux32.cmake <<EOF
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR i686)

#set(CMAKE_CXX_COMPILER_ARG "-m32")
#set(CMAKE_C_COMPILER_ARG "-m32")

set(cross_triple "i686-linux-gnu")

set(CMAKE_C_COMPILER $ENV{CC})
set(CMAKE_CXX_COMPILER $ENV{CXX})
set(CMAKE_Fortran_COMPILER $ENV{FC})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_IGNORE_PATH /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/lib/)

set(CMAKE_CROSSCOMPILING_EMULATOR /usr/${cross_triple}/bin/${cross_triple}-noop)
EOF

