# This workflow will upload docs to the gh-pages branch whenever something is pushed to master.

name: Docs
on:
  push:
    branches:
      - master

jobs:
  upload_docs:
    name: upload docs
    runs-on: ubuntu-latest
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish docs with Gradle
        run: gradle --stacktrace --info gitPublishPush
